/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolbarRouteImport } from './routes/toolbar'
import { Route as TimeRouteImport } from './routes/time'
import { Route as SurfacesRouteImport } from './routes/surfaces'
import { Route as StaticsRouteImport } from './routes/statics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesDemoRouteImport } from './routes/services-demo'
import { Route as OverlaysRouteImport } from './routes/overlays'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InputsAdvancedRouteImport } from './routes/inputs-advanced'
import { Route as GridNextRouteImport } from './routes/grid-next'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as DataLoaderRouteImport } from './routes/data-loader'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as ColorRouteImport } from './routes/color'
import { Route as CarouselRouteImport } from './routes/carousel'
import { Route as CanvasGridRouteImport } from './routes/canvas-grid'
import { Route as IndexRouteImport } from './routes/index'

const ToolbarRoute = ToolbarRouteImport.update({
  id: '/toolbar',
  path: '/toolbar',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const SurfacesRoute = SurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticsRoute = StaticsRouteImport.update({
  id: '/statics',
  path: '/statics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDemoRoute = ServicesDemoRouteImport.update({
  id: '/services-demo',
  path: '/services-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysRoute = OverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsAdvancedRoute = InputsAdvancedRouteImport.update({
  id: '/inputs-advanced',
  path: '/inputs-advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const GridNextRoute = GridNextRouteImport.update({
  id: '/grid-next',
  path: '/grid-next',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLoaderRoute = DataLoaderRouteImport.update({
  id: '/data-loader',
  path: '/data-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorRoute = ColorRouteImport.update({
  id: '/color',
  path: '/color',
  getParentRoute: () => rootRouteImport,
} as any)
const CarouselRoute = CarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasGridRoute = CanvasGridRouteImport.update({
  id: '/canvas-grid',
  path: '/canvas-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas-grid': typeof CanvasGridRoute
  '/carousel': typeof CarouselRoute
  '/color': typeof ColorRoute
  '/controls': typeof ControlsRoute
  '/data-loader': typeof DataLoaderRoute
  '/dates': typeof DatesRoute
  '/disclosure': typeof DisclosureRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/grid-next': typeof GridNextRoute
  '/inputs-advanced': typeof InputsAdvancedRoute
  '/kanban': typeof KanbanRoute
  '/overlays': typeof OverlaysRoute
  '/services-demo': typeof ServicesDemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statics': typeof StaticsRoute
  '/surfaces': typeof SurfacesRoute
  '/time': typeof TimeRoute
  '/toolbar': typeof ToolbarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas-grid': typeof CanvasGridRoute
  '/carousel': typeof CarouselRoute
  '/color': typeof ColorRoute
  '/controls': typeof ControlsRoute
  '/data-loader': typeof DataLoaderRoute
  '/dates': typeof DatesRoute
  '/disclosure': typeof DisclosureRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/grid-next': typeof GridNextRoute
  '/inputs-advanced': typeof InputsAdvancedRoute
  '/kanban': typeof KanbanRoute
  '/overlays': typeof OverlaysRoute
  '/services-demo': typeof ServicesDemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statics': typeof StaticsRoute
  '/surfaces': typeof SurfacesRoute
  '/time': typeof TimeRoute
  '/toolbar': typeof ToolbarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas-grid': typeof CanvasGridRoute
  '/carousel': typeof CarouselRoute
  '/color': typeof ColorRoute
  '/controls': typeof ControlsRoute
  '/data-loader': typeof DataLoaderRoute
  '/dates': typeof DatesRoute
  '/disclosure': typeof DisclosureRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/grid-next': typeof GridNextRoute
  '/inputs-advanced': typeof InputsAdvancedRoute
  '/kanban': typeof KanbanRoute
  '/overlays': typeof OverlaysRoute
  '/services-demo': typeof ServicesDemoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statics': typeof StaticsRoute
  '/surfaces': typeof SurfacesRoute
  '/time': typeof TimeRoute
  '/toolbar': typeof ToolbarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas-grid'
    | '/carousel'
    | '/color'
    | '/controls'
    | '/data-loader'
    | '/dates'
    | '/disclosure'
    | '/engine'
    | '/feedback'
    | '/grid-next'
    | '/inputs-advanced'
    | '/kanban'
    | '/overlays'
    | '/services-demo'
    | '/sitemap.xml'
    | '/statics'
    | '/surfaces'
    | '/time'
    | '/toolbar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas-grid'
    | '/carousel'
    | '/color'
    | '/controls'
    | '/data-loader'
    | '/dates'
    | '/disclosure'
    | '/engine'
    | '/feedback'
    | '/grid-next'
    | '/inputs-advanced'
    | '/kanban'
    | '/overlays'
    | '/services-demo'
    | '/sitemap.xml'
    | '/statics'
    | '/surfaces'
    | '/time'
    | '/toolbar'
  id:
    | '__root__'
    | '/'
    | '/canvas-grid'
    | '/carousel'
    | '/color'
    | '/controls'
    | '/data-loader'
    | '/dates'
    | '/disclosure'
    | '/engine'
    | '/feedback'
    | '/grid-next'
    | '/inputs-advanced'
    | '/kanban'
    | '/overlays'
    | '/services-demo'
    | '/sitemap.xml'
    | '/statics'
    | '/surfaces'
    | '/time'
    | '/toolbar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasGridRoute: typeof CanvasGridRoute
  CarouselRoute: typeof CarouselRoute
  ColorRoute: typeof ColorRoute
  ControlsRoute: typeof ControlsRoute
  DataLoaderRoute: typeof DataLoaderRoute
  DatesRoute: typeof DatesRoute
  DisclosureRoute: typeof DisclosureRoute
  EngineRoute: typeof EngineRoute
  FeedbackRoute: typeof FeedbackRoute
  GridNextRoute: typeof GridNextRoute
  InputsAdvancedRoute: typeof InputsAdvancedRoute
  KanbanRoute: typeof KanbanRoute
  OverlaysRoute: typeof OverlaysRoute
  ServicesDemoRoute: typeof ServicesDemoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaticsRoute: typeof StaticsRoute
  SurfacesRoute: typeof SurfacesRoute
  TimeRoute: typeof TimeRoute
  ToolbarRoute: typeof ToolbarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolbar': {
      id: '/toolbar'
      path: '/toolbar'
      fullPath: '/toolbar'
      preLoaderRoute: typeof ToolbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surfaces': {
      id: '/surfaces'
      path: '/surfaces'
      fullPath: '/surfaces'
      preLoaderRoute: typeof SurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statics': {
      id: '/statics'
      path: '/statics'
      fullPath: '/statics'
      preLoaderRoute: typeof StaticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-demo': {
      id: '/services-demo'
      path: '/services-demo'
      fullPath: '/services-demo'
      preLoaderRoute: typeof ServicesDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays': {
      id: '/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof OverlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs-advanced': {
      id: '/inputs-advanced'
      path: '/inputs-advanced'
      fullPath: '/inputs-advanced'
      preLoaderRoute: typeof InputsAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-next': {
      id: '/grid-next'
      path: '/grid-next'
      fullPath: '/grid-next'
      preLoaderRoute: typeof GridNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-loader': {
      id: '/data-loader'
      path: '/data-loader'
      fullPath: '/data-loader'
      preLoaderRoute: typeof DataLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color': {
      id: '/color'
      path: '/color'
      fullPath: '/color'
      preLoaderRoute: typeof ColorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carousel': {
      id: '/carousel'
      path: '/carousel'
      fullPath: '/carousel'
      preLoaderRoute: typeof CarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-grid': {
      id: '/canvas-grid'
      path: '/canvas-grid'
      fullPath: '/canvas-grid'
      preLoaderRoute: typeof CanvasGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasGridRoute: CanvasGridRoute,
  CarouselRoute: CarouselRoute,
  ColorRoute: ColorRoute,
  ControlsRoute: ControlsRoute,
  DataLoaderRoute: DataLoaderRoute,
  DatesRoute: DatesRoute,
  DisclosureRoute: DisclosureRoute,
  EngineRoute: EngineRoute,
  FeedbackRoute: FeedbackRoute,
  GridNextRoute: GridNextRoute,
  InputsAdvancedRoute: InputsAdvancedRoute,
  KanbanRoute: KanbanRoute,
  OverlaysRoute: OverlaysRoute,
  ServicesDemoRoute: ServicesDemoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaticsRoute: StaticsRoute,
  SurfacesRoute: SurfacesRoute,
  TimeRoute: TimeRoute,
  ToolbarRoute: ToolbarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
