/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualizationRouteImport } from './routes/virtualization'
import { Route as ThemingRouteImport } from './routes/theming'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DataGridRouteImport } from './routes/data-grid'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'

const VirtualizationRoute = VirtualizationRouteImport.update({
  id: '/virtualization',
  path: '/virtualization',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemingRoute = ThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGridRoute = DataGridRouteImport.update({
  id: '/data-grid',
  path: '/data-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/collections': typeof CollectionsRoute
  '/components': typeof ComponentsRoute
  '/data-grid': typeof DataGridRoute
  '/debug': typeof DebugRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theming': typeof ThemingRoute
  '/virtualization': typeof VirtualizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/collections': typeof CollectionsRoute
  '/components': typeof ComponentsRoute
  '/data-grid': typeof DataGridRoute
  '/debug': typeof DebugRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theming': typeof ThemingRoute
  '/virtualization': typeof VirtualizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/collections': typeof CollectionsRoute
  '/components': typeof ComponentsRoute
  '/data-grid': typeof DataGridRoute
  '/debug': typeof DebugRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/theming': typeof ThemingRoute
  '/virtualization': typeof VirtualizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/collections'
    | '/components'
    | '/data-grid'
    | '/debug'
    | '/sitemap.xml'
    | '/theming'
    | '/virtualization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/collections'
    | '/components'
    | '/data-grid'
    | '/debug'
    | '/sitemap.xml'
    | '/theming'
    | '/virtualization'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/collections'
    | '/components'
    | '/data-grid'
    | '/debug'
    | '/sitemap.xml'
    | '/theming'
    | '/virtualization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CollectionsRoute: typeof CollectionsRoute
  ComponentsRoute: typeof ComponentsRoute
  DataGridRoute: typeof DataGridRoute
  DebugRoute: typeof DebugRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThemingRoute: typeof ThemingRoute
  VirtualizationRoute: typeof VirtualizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtualization': {
      id: '/virtualization'
      path: '/virtualization'
      fullPath: '/virtualization'
      preLoaderRoute: typeof VirtualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theming': {
      id: '/theming'
      path: '/theming'
      fullPath: '/theming'
      preLoaderRoute: typeof ThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-grid': {
      id: '/data-grid'
      path: '/data-grid'
      fullPath: '/data-grid'
      preLoaderRoute: typeof DataGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  CollectionsRoute: CollectionsRoute,
  ComponentsRoute: ComponentsRoute,
  DataGridRoute: DataGridRoute,
  DebugRoute: DebugRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThemingRoute: ThemingRoute,
  VirtualizationRoute: VirtualizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
