/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualizationRouteImport } from './routes/virtualization'
import { Route as ToolbarRouteImport } from './routes/toolbar'
import { Route as TimeRouteImport } from './routes/time'
import { Route as ThemingRouteImport } from './routes/theming'
import { Route as SurfacesRouteImport } from './routes/surfaces'
import { Route as StaticsRouteImport } from './routes/statics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OverlaysRouteImport } from './routes/overlays'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InputsAdvancedRouteImport } from './routes/inputs-advanced'
import { Route as GridNextRouteImport } from './routes/grid-next'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as DatesRouteImport } from './routes/dates'
import { Route as DataLoaderRouteImport } from './routes/data-loader'
import { Route as DataGridRouteImport } from './routes/data-grid'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CarouselRouteImport } from './routes/carousel'
import { Route as CanvasGridRouteImport } from './routes/canvas-grid'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'

const VirtualizationRoute = VirtualizationRouteImport.update({
  id: '/virtualization',
  path: '/virtualization',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolbarRoute = ToolbarRouteImport.update({
  id: '/toolbar',
  path: '/toolbar',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemingRoute = ThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => rootRouteImport,
} as any)
const SurfacesRoute = SurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticsRoute = StaticsRouteImport.update({
  id: '/statics',
  path: '/statics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysRoute = OverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InputsAdvancedRoute = InputsAdvancedRouteImport.update({
  id: '/inputs-advanced',
  path: '/inputs-advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const GridNextRoute = GridNextRouteImport.update({
  id: '/grid-next',
  path: '/grid-next',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const DatesRoute = DatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLoaderRoute = DataLoaderRouteImport.update({
  id: '/data-loader',
  path: '/data-loader',
  getParentRoute: () => rootRouteImport,
} as any)
const DataGridRoute = DataGridRouteImport.update({
  id: '/data-grid',
  path: '/data-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CarouselRoute = CarouselRouteImport.update({
  id: '/carousel',
  path: '/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasGridRoute = CanvasGridRouteImport.update({
  id: '/canvas-grid',
  path: '/canvas-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/canvas-grid': typeof CanvasGridRoute
  '/carousel': typeof CarouselRoute
  '/collections': typeof CollectionsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/data-grid': typeof DataGridRoute
  '/data-loader': typeof DataLoaderRoute
  '/dates': typeof DatesRoute
  '/debug': typeof DebugRoute
  '/disclosure': typeof DisclosureRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/grid-next': typeof GridNextRoute
  '/inputs-advanced': typeof InputsAdvancedRoute
  '/kanban': typeof KanbanRoute
  '/overlays': typeof OverlaysRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statics': typeof StaticsRoute
  '/surfaces': typeof SurfacesRoute
  '/theming': typeof ThemingRoute
  '/time': typeof TimeRoute
  '/toolbar': typeof ToolbarRoute
  '/virtualization': typeof VirtualizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/canvas-grid': typeof CanvasGridRoute
  '/carousel': typeof CarouselRoute
  '/collections': typeof CollectionsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/data-grid': typeof DataGridRoute
  '/data-loader': typeof DataLoaderRoute
  '/dates': typeof DatesRoute
  '/debug': typeof DebugRoute
  '/disclosure': typeof DisclosureRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/grid-next': typeof GridNextRoute
  '/inputs-advanced': typeof InputsAdvancedRoute
  '/kanban': typeof KanbanRoute
  '/overlays': typeof OverlaysRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statics': typeof StaticsRoute
  '/surfaces': typeof SurfacesRoute
  '/theming': typeof ThemingRoute
  '/time': typeof TimeRoute
  '/toolbar': typeof ToolbarRoute
  '/virtualization': typeof VirtualizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/canvas-grid': typeof CanvasGridRoute
  '/carousel': typeof CarouselRoute
  '/collections': typeof CollectionsRoute
  '/components': typeof ComponentsRoute
  '/controls': typeof ControlsRoute
  '/data-grid': typeof DataGridRoute
  '/data-loader': typeof DataLoaderRoute
  '/dates': typeof DatesRoute
  '/debug': typeof DebugRoute
  '/disclosure': typeof DisclosureRoute
  '/engine': typeof EngineRoute
  '/feedback': typeof FeedbackRoute
  '/grid-next': typeof GridNextRoute
  '/inputs-advanced': typeof InputsAdvancedRoute
  '/kanban': typeof KanbanRoute
  '/overlays': typeof OverlaysRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statics': typeof StaticsRoute
  '/surfaces': typeof SurfacesRoute
  '/theming': typeof ThemingRoute
  '/time': typeof TimeRoute
  '/toolbar': typeof ToolbarRoute
  '/virtualization': typeof VirtualizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/canvas-grid'
    | '/carousel'
    | '/collections'
    | '/components'
    | '/controls'
    | '/data-grid'
    | '/data-loader'
    | '/dates'
    | '/debug'
    | '/disclosure'
    | '/engine'
    | '/feedback'
    | '/grid-next'
    | '/inputs-advanced'
    | '/kanban'
    | '/overlays'
    | '/sitemap.xml'
    | '/statics'
    | '/surfaces'
    | '/theming'
    | '/time'
    | '/toolbar'
    | '/virtualization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/canvas-grid'
    | '/carousel'
    | '/collections'
    | '/components'
    | '/controls'
    | '/data-grid'
    | '/data-loader'
    | '/dates'
    | '/debug'
    | '/disclosure'
    | '/engine'
    | '/feedback'
    | '/grid-next'
    | '/inputs-advanced'
    | '/kanban'
    | '/overlays'
    | '/sitemap.xml'
    | '/statics'
    | '/surfaces'
    | '/theming'
    | '/time'
    | '/toolbar'
    | '/virtualization'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/canvas-grid'
    | '/carousel'
    | '/collections'
    | '/components'
    | '/controls'
    | '/data-grid'
    | '/data-loader'
    | '/dates'
    | '/debug'
    | '/disclosure'
    | '/engine'
    | '/feedback'
    | '/grid-next'
    | '/inputs-advanced'
    | '/kanban'
    | '/overlays'
    | '/sitemap.xml'
    | '/statics'
    | '/surfaces'
    | '/theming'
    | '/time'
    | '/toolbar'
    | '/virtualization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CanvasGridRoute: typeof CanvasGridRoute
  CarouselRoute: typeof CarouselRoute
  CollectionsRoute: typeof CollectionsRoute
  ComponentsRoute: typeof ComponentsRoute
  ControlsRoute: typeof ControlsRoute
  DataGridRoute: typeof DataGridRoute
  DataLoaderRoute: typeof DataLoaderRoute
  DatesRoute: typeof DatesRoute
  DebugRoute: typeof DebugRoute
  DisclosureRoute: typeof DisclosureRoute
  EngineRoute: typeof EngineRoute
  FeedbackRoute: typeof FeedbackRoute
  GridNextRoute: typeof GridNextRoute
  InputsAdvancedRoute: typeof InputsAdvancedRoute
  KanbanRoute: typeof KanbanRoute
  OverlaysRoute: typeof OverlaysRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaticsRoute: typeof StaticsRoute
  SurfacesRoute: typeof SurfacesRoute
  ThemingRoute: typeof ThemingRoute
  TimeRoute: typeof TimeRoute
  ToolbarRoute: typeof ToolbarRoute
  VirtualizationRoute: typeof VirtualizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtualization': {
      id: '/virtualization'
      path: '/virtualization'
      fullPath: '/virtualization'
      preLoaderRoute: typeof VirtualizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolbar': {
      id: '/toolbar'
      path: '/toolbar'
      fullPath: '/toolbar'
      preLoaderRoute: typeof ToolbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theming': {
      id: '/theming'
      path: '/theming'
      fullPath: '/theming'
      preLoaderRoute: typeof ThemingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surfaces': {
      id: '/surfaces'
      path: '/surfaces'
      fullPath: '/surfaces'
      preLoaderRoute: typeof SurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statics': {
      id: '/statics'
      path: '/statics'
      fullPath: '/statics'
      preLoaderRoute: typeof StaticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays': {
      id: '/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof OverlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inputs-advanced': {
      id: '/inputs-advanced'
      path: '/inputs-advanced'
      fullPath: '/inputs-advanced'
      preLoaderRoute: typeof InputsAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid-next': {
      id: '/grid-next'
      path: '/grid-next'
      fullPath: '/grid-next'
      preLoaderRoute: typeof GridNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dates': {
      id: '/dates'
      path: '/dates'
      fullPath: '/dates'
      preLoaderRoute: typeof DatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-loader': {
      id: '/data-loader'
      path: '/data-loader'
      fullPath: '/data-loader'
      preLoaderRoute: typeof DataLoaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-grid': {
      id: '/data-grid'
      path: '/data-grid'
      fullPath: '/data-grid'
      preLoaderRoute: typeof DataGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carousel': {
      id: '/carousel'
      path: '/carousel'
      fullPath: '/carousel'
      preLoaderRoute: typeof CarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-grid': {
      id: '/canvas-grid'
      path: '/canvas-grid'
      fullPath: '/canvas-grid'
      preLoaderRoute: typeof CanvasGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  CanvasGridRoute: CanvasGridRoute,
  CarouselRoute: CarouselRoute,
  CollectionsRoute: CollectionsRoute,
  ComponentsRoute: ComponentsRoute,
  ControlsRoute: ControlsRoute,
  DataGridRoute: DataGridRoute,
  DataLoaderRoute: DataLoaderRoute,
  DatesRoute: DatesRoute,
  DebugRoute: DebugRoute,
  DisclosureRoute: DisclosureRoute,
  EngineRoute: EngineRoute,
  FeedbackRoute: FeedbackRoute,
  GridNextRoute: GridNextRoute,
  InputsAdvancedRoute: InputsAdvancedRoute,
  KanbanRoute: KanbanRoute,
  OverlaysRoute: OverlaysRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaticsRoute: StaticsRoute,
  SurfacesRoute: SurfacesRoute,
  ThemingRoute: ThemingRoute,
  TimeRoute: TimeRoute,
  ToolbarRoute: ToolbarRoute,
  VirtualizationRoute: VirtualizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
